name: CI tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Test files
        reuns-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v4
              with: 
                python-version: 3.10.8
                cache: pip

            - run: python -B -m pytest

