name: CI tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Test files
        runs-on: ubuntu-latest
        
        steps:
            - name: Copia arquivos
              uses: actions/checkout@v4
            
            - name: Roda outro comando
              run: echo $(ls)

            # - uses: actions/setup-python@v4
            #   with: 
            #     python-version: 3.10.8
            #     cache: pip
            # - run: pip install pytest      
            # - run: python -B -m pytest

